spring.application.name=gchat-viewer
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres1
spring.datasource.username=postgres1
spring.datasource.password=admin
server.servlet.context-path=/found
server.port=80
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB